### ISSUE TITLE
Unable to fetch response after fresh install

### ISSUE THREAD

**Issue by danrasmuson** [Aesthetikx/openai_pipe#8]
After install openai_pipe (gem install openai_pipe) and providing the token

```
❯  gem install openai_pipe
❯ ruby -v
ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]
````

I get this error `Unable to fetch response: undefined method `to_json' for an instance of Hash`

```
❯ openai_pipe hi
Unable to fetch response: undefined method `to_json' for an instance of Hash. /opt/homebrew/lib/ruby
/gems/3.3.0/gems/ruby-openai-3.7.0/lib/openai/client.rb:66:in `json_post'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/ruby-openai-3.7.0/lib/openai/client.rb:15:in `completions'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/quick_openai-0.1.3/lib/quick_openai/gpt3.rb:14:in `block in g
pt3'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/quick_openai-0.1.3/lib/quick_openai.rb:20:in `fetch_response_
from_client'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/quick_openai-0.1.3/lib/quick_openai/gpt3.rb:13:in `gpt3'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/quick_openai-0.1.3/lib/quick_openai/extensions/string.rb:7:in
 `gpt3'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/openai_pipe-0.1.3/lib/openai_pipe.rb:17:in `exe'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/openai_pipe-0.1.3/exe/openai_pipe:5:in `<top (required)>'
/opt/homebrew/lib/ruby/gems/3.3.0/bin/openai_pipe:25:in `load'
/opt/homebrew/lib/ruby/gems/3.3.0/bin/openai_pipe:25:in `<main>'
```

**Comment by danrasmuson** [comment]
Loz is working for me https://github.com/joone/loz
